# Dataset config
USER_ID_FIELD: HADM_ID
ITEM_ID_FIELD: NDC
RATING_FIELD: label
#   File "D:\OneDrive\Projects\RecBole-MetaRec\recbole_metarec\model\FOMeLU\FOMeLUTrainer.py", line 62, in _train_epoch
#    loss, grad = self.model.calculate_loss(taskBatch)
#  File "D:\OneDrive\Projects\RecBole-MetaRec\recbole_metarec\model\FOMeLU\FOMeLU.py", line 97, in calculate_loss
#    spt_x, spt_y, qrt_x, qrt_y=self.taskDesolveEmb(task)
#  File "D:\OneDrive\Projects\RecBole-MetaRec\recbole_metarec\model\FOMeLU\FOMeLU.py", line 51, in taskDesolveEmb
#    spt_x=self.embeddingTable.embeddingAllFields(task.spt)
#  File "D:\OneDrive\Projects\RecBole-MetaRec\recbole_metarec\MetaUtils.py", line 238, in embeddingAllFields
#    feature=self.embeddingSingleField(field,interaction[field])
#  File "D:\OneDrive\Projects\RecBole-MetaRec\recbole_metarec\MetaUtils.py", line 226, in embeddingSingleField
#    return torch.reshape(batchX,shape=(batchX.shape[0],1))
#RuntimeError: shape '[356, 1]' is invalid for input of size 712
# 本库代码在处理float类型数值列存在问题，暂时先删除float的数值列
# numerical_features: [DRUG_TYPE_MAIN_Proportion, DRUG_TYPE_BASE_Proportion, DRUG_TYPE_ADDITIVE_Proportion]
#load_col:
#    item: [NDC, FORM_UNIT_DISP_Freq_1, FORM_UNIT_DISP_Freq_2, FORM_UNIT_DISP_Freq_3, FORM_UNIT_DISP_Freq_4, FORM_UNIT_DISP_Freq_5]


load_col:                       # (dict) The suffix of atomic files: (list) field names to be loaded.
    item: [NDC, FORM_UNIT_DISP_Freq_1, FORM_UNIT_DISP_Freq_2, FORM_UNIT_DISP_Freq_3, FORM_UNIT_DISP_Freq_4, FORM_UNIT_DISP_Freq_5]
    # item: [NDC, DRUG_TYPE_MAIN_Proportion, DRUG_TYPE_BASE_Proportion, DRUG_TYPE_ADDITIVE_Proportion,  FORM_UNIT_DISP_Freq_1, FORM_UNIT_DISP_Freq_2, FORM_UNIT_DISP_Freq_3, FORM_UNIT_DISP_Freq_4, FORM_UNIT_DISP_Freq_5]
    user: [HADM_ID, ADMISSION_TYPE, ADMISSION_LOCATION, DISCHARGE_LOCATION, INSURANCE, LANGUAGE, RELIGION, MARITAL_STATUS, ETHNICITY]
    inter: [HADM_ID, NDC, label] # DRUG_TYPE, PROD_STRENGTH, DOSE_VAL_RX, DOSE_UNIT_RX, FORM_VAL_DISP, FORM_UNIT_DISP, ROUTE, ROW_ID]
unload_col: ~                   # (dict) The suffix of atomic files: (list) field names NOT to be loaded.
unused_col: ~                   # (dict) The suffix of atomic files: (list) field names which are loaded but not used.
# numerical_features: [DRUG_TYPE_MAIN_Proportion, DRUG_TYPE_BASE_Proportion, DRUG_TYPE_ADDITIVE_Proportion]
normalize_all: False
# user_inter_num_interval: [13,100]

# Training and evaluation config
seed: 1128
epochs: 50
train_batch_size: 32
valid_metric: AUC
train_neg_sample_args:
  distribution: uniform
  sample_num: 0

# Benchmark .inter file
benchmark_filename: ["train", "valid", "test"]           # (list) List of pre-split user-item interaction suffix.

# Evaluate config
eval_args:
    group_by: task
    order: RO
    split: ~
    mode : labeled

# Meta learning config
meta_args:
    support_num: none
    query_num: 10

# LWA Parameters
embedding: 32
embeddingHiddenDim: 64
lr: 0.0001

# Metrics
# metrics: ['precision','recall','hit','ndcg']
metrics: ['AUC', 'LogLoss']
metric_decimal_place: 4
